#ifndef __MAIN_H__
#define __MAIN_H__
#include <stm32f4xx.h>


//云台调试模式
#define	PAN_NORMAL										1 //云台正常

#define	YAW_CHASSIS_DEBUG							0 //YAW调参 以底盘为参考
#define YAW_CHASSIS_POSITION_DEBUG 		0//YAW位置环调节 以底盘为参考
#define YAW_CHASSIS_VELOCITY_DEBUG 		0//速度环调节

#define	YAW_GROUND_DEBUG							0 //YAW调参 以地面为参考
#define YAW_GROUND_POSITION_DEBUG			0//YAW位置环调节 以地面为参考
#define YAW_GROUND_VELOCITY_DEBUG 		0//速度环调节 以地面为参考

#define	PITCH_CHASSIS_DEBUG						0 //PITCH调参 以底盘为参考
#define PITCH_CHASSIS_POSITION_DEBUG 	0//PITCH位置环调节 以底盘为参考
#define PITCH_CHASSIS_VELOCITY_DEBUG 	0//PITCH速度环调节 以底盘为参考

#define	PITCH_GROUND_DEBUG						0 //PITCH调参 以地面为参考
#define PITCH_GROUND_POSITION_DEBUG 	0
#define PITCH_GROUND_VELOCITY_DEBUG 	0

#if ((PITCH_GROUND_VELOCITY_DEBUG || PITCH_GROUND_POSITION_DEBUG || PITCH_GROUND_DEBUG || PAN_NORMAL || YAW_CHASSIS_DEBUG || YAW_CHASSIS_POSITION_DEBUG || YAW_CHASSIS_VELOCITY_DEBUG || YAW_GROUND_DEBUG || YAW_GROUND_POSITION_DEBUG || YAW_GROUND_VELOCITY_DEBUG || PITCH_CHASSIS_DEBUG || PITCH_CHASSIS_POSITION_DEBUG || PITCH_CHASSIS_VELOCITY_DEBUG)==0)
	#error 请选择调试模式

#elif ((PITCH_GROUND_VELOCITY_DEBUG + PITCH_GROUND_POSITION_DEBUG + PITCH_GROUND_DEBUG + PAN_NORMAL + YAW_CHASSIS_DEBUG + YAW_CHASSIS_POSITION_DEBUG + YAW_CHASSIS_VELOCITY_DEBUG + YAW_GROUND_DEBUG + YAW_GROUND_POSITION_DEBUG + YAW_GROUND_VELOCITY_DEBUG + PITCH_CHASSIS_DEBUG + PITCH_CHASSIS_POSITION_DEBUG + PITCH_CHASSIS_VELOCITY_DEBUG)>1)
	#error 模式重复选择！！！
#endif

#endif
